# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wage_determinations', '0003_rate_fts_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage', models.TextField()),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_classification', models.TextField()),
                ('date', models.DateField()),
                ('hours', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dollars', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FringeException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.TextField()),
                ('explanation', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('zip_code', models.TextField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage_determinations.County')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage_determinations.State')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.TextField()),
                ('period_end', models.DateField()),
                ('date_filed', models.DateField(auto_now_add=True)),
                ('signer_name', models.TextField()),
                ('fringe_benefit_programs', models.BooleanField(default=False)),
                ('fringe_benefit_cash', models.BooleanField(default=False)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Contractor')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollars_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dol_rate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='wage_determinations.Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.TextField()),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number_withholding_exceptions', models.IntegerField(default=0)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Payroll')),
            ],
        ),
        migrations.AddField(
            model_name='payrollline',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Worker'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Project'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fringeexception',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Payroll'),
        ),
        migrations.AddField(
            model_name='deduction',
            name='payroll_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.PayrollLine'),
        ),
        migrations.AddField(
            model_name='day',
            name='payroll_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.PayrollLine'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payrolls.Location'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to=settings.AUTH_USER_MODEL),
        ),
    ]
