# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='date_filed',
        ),
        migrations.AddField(
            model_name='payroll',
            name='date_submitted_to_gov',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='date_submitted_to_parent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='parent_contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_contractor', to='payrolls.Contractor'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='parent_payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrolls.Payroll'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollline',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payrollline',
            name='dollars_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
