# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:52
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('payrolls', '0005_auto_20160501_2310'), ]

    operations = [
        migrations.AddField(model_name='payroll',
                            name='is_current',
                            field=models.BooleanField(default=True), ),
        migrations.AddField(
            model_name='payroll',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True,
                                       default=datetime.datetime(
                                           2016, 5, 11, 19, 52, 8, 330748)),
            preserve_default=False, ),
        migrations.AddField(model_name='payrollupload',
                            name='payroll',
                            field=models.ForeignKey(
                                blank=True,
                                default=1,
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Payroll'),
                            preserve_default=False, ),
    ]
