# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 17:03
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wage_determinations', '0005_auto_20160506_0956'),
        ('payrolls', '0006_auto_20160511_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('dollars', models.DecimalField(decimal_places=2,
                                                max_digits=6)),
            ], ),
        migrations.CreateModel(name='ProjectContractor',
                               fields=[
                                   ('id', models.AutoField(auto_created=True,
                                                           primary_key=True,
                                                           serialize=False,
                                                           verbose_name='ID')),
                               ], ),
        migrations.CreateModel(
            name='Withholding',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('purpose', models.TextField()),
                ('dollars', models.DecimalField(blank=True,
                                                decimal_places=2,
                                                max_digits=6)),
            ], ),
        migrations.CreateModel(name='Workweek',
                               fields=[
                                   ('id', models.AutoField(auto_created=True,
                                                           primary_key=True,
                                                           serialize=False,
                                                           verbose_name='ID')),
                                   ('number_withholding_exceptions',
                                    models.IntegerField(default=0)),
                                   ('special', models.TextField(blank=True)),
                               ], ),
        migrations.RemoveField(model_name='deduction',
                               name='payroll_line', ),
        migrations.AlterModelOptions(name='day',
                                     options={'ordering': ('date', )}, ),
        migrations.RemoveField(model_name='day',
                               name='job_name', ),
        migrations.RemoveField(model_name='day',
                               name='work_classification', ),
        migrations.RemoveField(model_name='payrollline',
                               name='worker', ),
        migrations.RemoveField(model_name='worker',
                               name='payroll', ),
        migrations.AddField(model_name='payroll',
                            name='status',
                            field=models.TextField(null=True), ),
        migrations.AddField(model_name='payrollline',
                            name='job_name',
                            field=models.TextField(default=''),
                            preserve_default=False, ),
        migrations.AddField(model_name='payrollline',
                            name='work_classification',
                            field=models.TextField(blank=True), ),
        migrations.AddField(model_name='project',
                            name='contract_number',
                            field=models.TextField(default=''),
                            preserve_default=False, ),
        migrations.AddField(
            model_name='project',
            name='dol_rates',
            field=models.ManyToManyField(to='wage_determinations.Rate'), ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateField(default=datetime.datetime.today()),
            preserve_default=False, ),
        migrations.AddField(model_name='worker',
                            name='contractor',
                            field=models.ForeignKey(
                                default=0,
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Contractor'),
                            preserve_default=False, ),
        migrations.AddField(model_name='worker',
                            name='identifier',
                            field=models.TextField(db_index=True,
                                                   default=0),
                            preserve_default=False, ),
        migrations.AlterField(model_name='contractor',
                              name='cage',
                              field=models.TextField(db_index=True), ),
        migrations.AlterField(model_name='contractor',
                              name='name',
                              field=models.TextField(db_index=True), ),
        migrations.AlterField(model_name='payroll',
                              name='parent_payroll',
                              field=models.ForeignKey(
                                  blank=True,
                                  null=True,
                                  on_delete=django.db.models.deletion.CASCADE,
                                  related_name='child_payroll',
                                  to='payrolls.Payroll'), ),
        migrations.DeleteModel(name='Deduction', ),
        migrations.AddField(model_name='workweek',
                            name='payroll',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Payroll'), ),
        migrations.AddField(model_name='workweek',
                            name='worker',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Worker'), ),
        migrations.AddField(model_name='withholding',
                            name='worker',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Worker'), ),
        migrations.AddField(model_name='projectcontractor',
                            name='contractor',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Contractor'), ),
        migrations.AddField(model_name='projectcontractor',
                            name='project',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Project'), ),
        migrations.AddField(model_name='projectcontractor',
                            name='subcontracting_from',
                            field=models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='subcontractor',
                                to='payrolls.Contractor'), ),
        migrations.AddField(model_name='linequantity',
                            name='payroll_line',
                            field=models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.PayrollLine'), ),
        migrations.AddField(
            model_name='payroll',
            name='workers',
            field=models.ManyToManyField(through='payrolls.Workweek',
                                         to='payrolls.Worker'), ),
        migrations.AddField(model_name='payrollline',
                            name='workweek',
                            field=models.ForeignKey(
                                default=0,
                                on_delete=django.db.models.deletion.CASCADE,
                                to='payrolls.Workweek'),
                            preserve_default=False, ),
    ]
