# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 17:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dollars_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fringe', models.TextField()),
                ('group_qualifier', models.TextField(blank=True)),
                ('construction_type', models.TextField()),
                ('construction_subtype', models.TextField(blank=True)),
                ('construction_qualifier', models.TextField(blank=True)),
                ('construction_survey_qualifier', models.TextField(blank=True)),
                ('occupation', models.TextField()),
                ('occupation_qualifier', models.TextField(blank=True)),
                ('rate_name', models.TextField(blank=True)),
                ('rate_name_qualifier', models.TextField(blank=True)),
                ('subrate_name', models.TextField(blank=True)),
                ('subrate_name_qualifier', models.TextField(blank=True)),
                ('location_qualifier', models.TextField(blank=True)),
                ('counties', models.ManyToManyField(to='wage_determinations.County')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WageDetermination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('header', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('published_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='determination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage_determinations.WageDetermination'),
        ),
        migrations.AddField(
            model_name='county',
            name='us_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wage_determinations.State'),
        ),
    ]
